version: '3.8'

services:
  db_postgres:
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
      POSTGRES_DB: 'coleguito'
      POSTGRES_USER: 'colega'
      POSTGRES_PASSWORD: 'xipae7eoG0iev3ahZahm0weetheexoug'
    ports:
      - '50432:5432'
    expose:
      - '5432'
#    volumes:
#      - "./database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql"

  hw_app:
    build:
      context: .
    expose:
      - '8080'
    depends_on:
      - db_postgres
